# Site
name: "Ars Trivialis"
title: "Ars Trivialis"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: ''
disqus: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  thiago:
    name: Thiago Mosqueiro
    avatar: 'assets/images/thiagoavatar.jpg'
    display_name: Thiago Mosqueiro
    web: https://thmosqueiro.vandroiy.com
    twitter: https://twitter.com/thmosqueiro
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  tiago:
    name: Tiago
    display_name: Tiago
    avatar: 'assets/images/tiagoavatar.jpg'
    twitter: https://twitter.com/tejotaefe
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
